### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gertjanvanzwieten** [nutils/nutils#101]
Missing: an introductory document that explains fundamental concepts like topologies and functions.

**Comment by CVerhoosel** [comment]
Sorry for opening my response as a new issue. Anyway, curous to hear what others think about this. See #102.

**Comment by timovanopstal** [comment]
I like Clemens' idea of putting it in a presentation format (that encourages diagrams, bullet lists and schematics and discourages long paragraphs)

Another thing I'm thinking is maybe to have a tutorial, maybe extending the comments in one of the examples so that someone gets a walk through of the basic workflow (and can compare to other examples to see what the different possibilities are)

**Comment by timovanopstal** [comment]
One additional comment, I mentioned [Open Software Publications](http://www.journals.elsevier.com/science-of-computer-programming/call-for-software/a-new-software-track-on-original-software-publications-scico/) yesterday, as a way to make Nutils citable in our papers and to gain visibility in the community. It was mentioned that such a publication could grow out of our documentation, but also that we shouldn't get side-tracked pouring too much time into such an OSP. Posted here for reference and further discussion.

**Comment by MShokrpour** [comment]
I am not sure if it is also other people's preferences, but what I personally prefer is a documentation (more in presentation format as Clemens suggested) to start with a map (or charts) with hierarchies according to different Nutils' functions. I am more talking about an info-graph which creates sort of basic information about the Nutil's structure and functioning with the short explanation for each. That would speed up starting-phase with Nutils and we can hang it in the offices. Of course, then it can be extended to more details of inside-functioning and tutorials. 
Another thing which I found useful (with experience of working with masters students), is that the story of Nutils' functions can be given aligned with a FEM code-story. Clemens has a nice slide in his "scientific programming" course (lecture 5, slide 28) which can be inspiring for this matter.

**Comment by CVerhoosel** [comment]
The slide Mahnaz refers to:

![screenshot from 2016-03-30 15-18-55](https://cloud.githubusercontent.com/assets/5843082/14143296/ce023852-f68a-11e5-98e7-c25a06bff3c0.png)

**Comment by hgarikap** [comment]
I too agree that a flow chart or diagrams is effective way of documentation. But for a start, we can do a 1-2 page document -something like a "cheatsheet for nutils",  where basic functions that are needed can be defined- domain, geometry, mesh, setup BC/IC, solver an plotting tools.

**Comment by CVerhoosel** [comment]
I had a look at Timo's Open Software Publications suggestion. I like the idea, but my impression is that such a publication will not serve well as a "getting started" document. I'm interested in hearing what others think about this?

**Comment by joostvanzwieten** [comment]
I've written a small getting started document for students at the TU Delft: [nutils by example].

[nutils by example]: https://joostvanzwieten.github.io/nutils-by-example/

**Comment by CVerhoosel** [comment]
I love it Joost. In particular I like the style of presentation. Thanks for this great work. We should make sure that this becomes easily accessible.

**Comment by joostvanzwieten** [comment]
I will try to merge the presentation into the nutils documentation.

**Comment by VikingScientist** [comment]
Though I do like your introduction @joostvanzwieten, I fear that it is outdated with the release of nutils v.3.0. I would appreciate it if you could update it.

**Comment by timovanopstal** [comment]
@VikingScientist great you're using Nutils! Sorry about the outdated introduction, this is actually something I was going to pick up.
