### ISSUE TITLE
Documentation/working document

### ISSUE THREAD

**Issue by CVerhoosel** [nutils/nutils#102]
There should be a document that can be used to get people started with nutils. Personally I do not care about the exact form. A (elaborate) presentation would also work presumably. Of course, at some point in time, source code documentation should also be improved, but in my opinion that is not the top priority at this moment.

I'm curious to hear what others think about this. It would be great if we could come up with a concrete plan to develop this working document.

Of course the BDFL will play an essential role in the development of this document, but it is not solely his responsibility. All nutils users should be committed to work on this.

**Comment by timovanopstal** [comment]
wait... is this #101?

**Comment by gertjanvanzwieten** [comment]
Indeed, closing as duplicate
