### ISSUE TITLE
WinPython raise UnsupportedOperation("IOStream has no fileno.")

### ISSUE THREAD

**Issue by amorphousvn** [nutils/nutils#194]
WinPython 3.4.4 raises the following error when running the latest nutils (21 Feb 2017):

> File "F:\My_Programs\WinPython-64bit-3.4.4.3Qt5\python-3.4.4.amd64\lib\site-packages\ipykernel\iostream.py", line 306, in fileno
    raise **UnsupportedOperation("IOStream has no fileno.")**

**Comment by joostvanzwieten** [comment]
I think I fixed the issue in branch `fix-isatty`, but I can't test it: I don't have WinPython. Can you give branch `fix-isatty` a try?

**Comment by amorphousvn** [comment]
Thanks Joost, that bug is fixed :-)
