### ISSUE TITLE
Prevalence of top-level lambdas makes pickling difficult

### ISSUE THREAD

**Issue by TheBB** [nutils/nutils#213]
In `function.py` there's about 50 functions defined as top-level lambdas.

```python
zeros_like = lambda arr: zeros( arr.shape, _jointdtype(arr.dtype) )
```

This is nice for brevity but functionally not the same as a regular *def*. In particular, lambdas can't be pickled, while module-level *def*s can.

For example, this fails.

```python
domain, geom = mesh.rectilinear([[-1, 1]])
h = function.heaviside(geom)  # the resulting object references the function.zeros_like object
pickle.dumps(h)
```

Rewriting `zeros_like` in `def` form makes it work.

**Comment by TheBB** [comment]
This is a trivial rewrite that I don't mind doing if it'll be accepted.

**Comment by gertjanvanzwieten** [comment]
Thanks, that's a good point and we'll certainly accept the rewrite. However at this point I'm extensively reworking the function module which might affect some of these lambdas, so for best use of time you might want to hold off until that is merged (hopefully within two weeks from now).
