### ISSUE TITLE
replace stack-based with context-based config and read user config in cli.run

### ISSUE THREAD

**Issue by joostvanzwieten** [nutils/nutils#237]
Proposed syntax:

    nutils.config.attr # old value
    with nutils.config(attr=new_value):
      nutils.config.attr # new_value
    nutils.config.attr # old value

**Comment by TheBB** [comment]
Strongly encouraging some work on this. I just spent a fair amount of time trying to figure out why

```python
def test():
    with log.context('hi'):
        log.info('hello')
test()
```

prints `hello`, whereas

```python
@log.title
def test():
    with log.context('hi'):
        log.info('hello')
test()
```

prints `test · hi · hello`…
