### ISSUE TITLE
StructuredTopology.linearfunc

### ISSUE THREAD

**Issue by timovanopstal** [nutils/nutils#59]
Does line 955 in topology.py of the current commit (72c7d517571f66456cfc6810aa16a30ab6a87566) purposely disable an otherwise perfectly usable linearfunc() inherited from its parent class?

**Comment by gertjanvanzwieten** [comment]
Wow, no, that's weird. Fixed in a91c44f. I will start adding deprecation warnings to linearfunc/splinefunc/discontfunc soon as the new recommended syntax is basis( 'linear', .. ), and *func will be removed some time after releasing 2.0.
