### ISSUE TITLE
outdir property in nutilsrc stopped working

### ISSUE THREAD

**Issue by CVerhoosel** [nutils/nutils#66]
(9e3ebd2 or earlier) The output is written to public_html, despite the provision of a manually set "outdir" property in the nutilsrc file.

**Comment by gertjanvanzwieten** [comment]
Apologies, I forgot to put that in the Changelog (will add it now). The property 'outdir' was renamed to 'outrootdir'; please update your nutilsrc and everything will be back in working order. I'll elaborate a bit on the why of this change in the upcoming Changelog entry.
