### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by timovanopstal** [nutils/nutils#67]
function.py:20
Two lines seem to have disappeared here, noticed because the grammar is now wrong.
Secondly, lever=level? Good idea to pull the documentation through a spell check before the next release maybe?
ps. Notwithstanding, I very much like the documentation, and am surprised it took me a year to stumble across this issue ;-)

**Comment by gertjanvanzwieten** [comment]
Fixed in edbf096, thanks for spotting! Also, spell check before release, check!
