### ISSUE TITLE
Definition of function.jump counter-intuitive

### ISSUE THREAD

**Issue by CVerhoosel** [nutils/nutils#90]
The jump as defined in function.py seems somewhat counter-intuitive. It would be preferable to define it as the opposite minus self.

**Comment by joostvanzwieten** [comment]
I totally agree!

**Comment by gertjanvanzwieten** [comment]
Right, I also agree. The question then becomes whether we change this (and
break everyone's code) now, or after releasing 2.0. I was leaning towards
the latter initially, but considering that not that many people are doing
DG yet and that it will be more confusing to have this difference between
major versions I propose we fix this directly.

**Comment by CVerhoosel** [comment]
I am in favor of fixing it right away.

**Comment by gertjanvanzwieten** [comment]
Fixed in 49d6cc2. NOTE: this will BREAK all codes that use the jump operator, typically DG codes. The solution is simply to negate all present occurrences.
